<a href="https://colab.research.google.com/github/Skaveza/ml_practice/blob/main/Linearsystems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
A = np.array([
        [-1, 3],
        [3, 2]
    ], dtype=np.dtype(float))

b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")



Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]
Shape of A: (2, 2)
Shape of b: (2,)


In [10]:
x=np.linalg.solve(A, b)
print(f"Solution: {x}")


Solution: [-1.  2.]


In [11]:
d = np.linalg.det(A)

print(f"Determinant of matrix A: {d:.2f}")

Determinant of matrix A: -11.00


In [12]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [13]:
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00
